language: cpp
sudo: false
addons:
  apt:
    sources:
    - boost-latest
    packages:
    - libboost-regex1.55-dev
    - libboost-program-options1.55-dev
    - libboost-system1.55-dev
    - libboost-filesystem1.55-dev
compiler:
  - clang
before_script: 
  - cmake .
script:
  - make
  - bin/manalyze --version